# -*- coding: utf-8 -*-
"""demand_simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-qq-9R_aIcUOEelLeGJPt4TYBBS0rIND
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# =========================
# 1. DATA GENERATION
# =========================
np.random.seed(42)

date = pd.date_range(start="2024-01-01", periods=180)

data = pd.DataFrame({
    "date": date,
    "weekday": date.dayofweek,
    "promotion": np.random.choice([0, 1], size=180, p=[0.7, 0.3])
})

# =========================
# 2. DEMAND SIMULATION
# =========================
base = np.random.randint(80, 150, size=180)
seasonality = np.sin(np.arange(180) / 10) * 15

data["demand"] = base + seasonality + data["promotion"] * 20
data["demand"] = data["demand"].clip(50, 250)

# =========================
# 3. EXPLORATORY ANALYSIS
# =========================
print("\nSummary Statistics:\n", data.describe())

promo_effect = data.groupby("promotion")["demand"].mean()
print("\nPromotion Effect on Demand:\n", promo_effect)

# =========================
# 4. VISUALIZATION: ACTUAL DEMAND
# =========================
plt.figure(figsize=(12,5))
plt.plot(data["date"], data["demand"])
plt.title("Simulated Logistics Demand Trend")
plt.xlabel("Date")
plt.ylabel("Demand")
plt.grid(True)
plt.show()

# =========================
# 5. FORECASTING (MOVING AVERAGE)
# =========================
data["forecast"] = data["demand"].rolling(window=7, min_periods=1).mean()

# =========================
# 6. VISUALIZATION: ACTUAL vs FORECAST
# =========================
plt.figure(figsize=(12,5))
plt.plot(data["date"], data["demand"], label="Actual Demand")
plt.plot(data["date"], data["forecast"], label="7-Day Moving Average", linestyle="--")
plt.title("Actual vs Forecast Demand")
plt.xlabel("Date")
plt.ylabel("Demand")
plt.legend()
plt.grid(True)
plt.show()

# =========================
# 7. ERROR METRIC (MAE)
# =========================
data["error"] = abs(data["demand"] - data["forecast"])

mae = data["error"].mean()
print(f"\nMean Absolute Error (MAE): {mae:.2f}")

# =========================
# 8. EXPORT DATA
# =========================
data.to_csv("logistics_demand_simulation.csv", index=False)
print("\nDataset saved successfully.")

